### ISSUE TITLE
fullscreen touch control

### ISSUE THREAD

**Issue by K4thos** [Northfear/fheroes2-vita-old#1]
currently using 640x480 resolution stretched to fullscreen breaks the touch controls (cursor shows up in wrong place). Same problem when trying to use lower 16:9 resolutions, like 480x272. From what I see there is a commit titled "fullscreen touch control fix". Any chance for releasing 1.1 version with that fix?

**Comment by Northfear** [comment]
Yeah, it was fixed a while ago. I've uploaded a new version. Hopefully it's a latest one (got no Vita with me to test it right now)
