### ISSUE TITLE
Make errors

### ISSUE THREAD

**Issue by Zeepblok** [Northfear/fheroes2-vita-old#2]
Hi,

I have a few make errors. it goes ok for a while but after some time it gives the following errors:
 undefined reference to `FLAC__stream_decoder_finish'
 undefined reference to `MikMod_InfoLoader'
undefined reference to `mpg123_format'

What do I need to install for this? I installed all the prerequisites

**Comment by Northfear** [comment]
Yeah, sld2 updates from VitaSDK can add new dependencies over time. You may need to links new libs when building with other sdl versions than mine.
Glad that you figured it out.
